translations = {
    # Allgemeine Nachrichten
    'msg_welcome': '🎉 Willkommen im Smart Download Center!\nDeine All-in-One-Lösung zum Herunterladen von Videos und Audios von den beliebtesten Plattformen – einfach und schnell.\n\n🔹 Unterstützte Plattformen:\nInstagram | Facebook | TikTok | Pinterest | Snapchat\n✔️ Direktes Herunterladen von Videos oder Audios von jedem Link\n\n🔹 YouTube – Auf fortgeschrittenem Niveau:\n✔️ Video- oder Audio-Download\n✔️ Vollständige Playlist-Unterstützung\n✔️ Playlist durchsuchen, bestimmte Dateien auswählen oder alles herunterladen\n✔️ Format wählen: Video oder Audio nach Wunsch\n\n💡 Alles, was du tun musst: Sende einfach den Link\nIch kümmere mich um den Rest — präzise und schnell.\n\n🚀 Bereit? Sende jetzt deinen ersten Link.',
    'msg_help': '📝 Verwenden Sie /help, um alle verfügbaren Befehle anzuzeigen',
    'msg_settings': '⚙️ Einstellungen',
    'msg_error_unknown': '❌ Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.',
    'msg_subscription_required': '🔒 Um alle Bot-Funktionen nutzen zu können, musst du zuerst die folgenden Kanäle abonnieren:\n\n{channels}\n\n✅ Nach dem Abonnieren klicke unten auf "Abonnement prüfen".\n\nWenn die Kanäle nicht angezeigt werden, versuche es später erneut.',
    'msg_profile': '👤 Ihr Profil',
    'msg_stats': '📊 Ihre persönlichen Statistiken',
    'msg_admin_panel': '👑 Admin-Panel',
    'msg_broadcast': '📢 Broadcast-Nachricht senden',
    'msg_download_menu': '📥 Dateien herunterladen',
    'msg_detailed_report': '📊 Detaillierter Bericht',
    'msg_no_stats': '❌ Keine Statistiken verfügbar',
    'msg_user_banned': '🚫 Sie wurden vom Bot gesperrt.\nGrund: {reason}\n\nBei Fragen wenden Sie sich an den Admin.',
    'msg_user_already_banned': '⚠️ Benutzer ist bereits gesperrt.',
    'msg_user_not_found': '❌ Benutzer nicht gefunden.',
    'msg_ban_success': '✅ Benutzer erfolgreich gesperrt.',
    'msg_unban_success': '✅ Benutzer erfolgreich entsperrt.',
    'msg_maintenance': '🔧 Wartungshinweis\n\nSystemwartung wird durchgeführt:\n📅 Datum: {maintenance_date}\n⏰ Zeit: {maintenance_time}\n⏱️ Erwartete Dauer: {duration}\n\nWir entschuldigen uns für Unannehmlichkeiten.',
    'msg_system_update': '🆕 System-Update\n\nEin neues Update wurde veröffentlicht:\n📋 Version: {version}\n✨ Neue Funktionen:\n{features}\n\nDas Update ist jetzt verfügbar!',
    'msg_admin_message': '📢 Nachricht vom Admin\n\n{message_content}',
    'msg_achievement': 'Herzlichen Glückwunsch! Sie haben eine neue Auszeichnung erhalten:\n\n{achievement_icon} {achievement_name}\n{achievement_description}\n\n🏆 Erhaltene Punkte: {points_earned}',
    'msg_security_alert': '🚨 Sicherheitswarnung\n\nWarnungstyp: {alert_type}\nDetails: {details}\n\nBitte ergreifen Sie sofort geeignete Maßnahmen.',
    # Allgemeine Buttons
    'button_settings': '⚙️ Einstellungen',
    'button_back': '🔙 Zurück',
    'button_language_ar': '🇮🇶 Arabisch',
    'button_language_en': '🌐 Englisch',
    'button_timezone': '⏰ Zeitzone',
    'button_notifications': '🔔 Benachrichtigungen',
    'button_check_subscription': '✅ Abonnement prüfen',
    'button_main_menu': '🏠 Hauptmenü',
    'button_download_menu': '📥 Dateien herunterladen',
    'button_user_stats': '📊 Meine Statistiken',
    'button_admin_panel': '👑 Admin-Panel',
    'button_help': '🆘 Hilfe',
    'button_detailed_stats': '📊 Detaillierte Statistiken',
    'button_download_history': '📥 Download-Verlauf',
    'button_users_management': '👥 Benutzerverwaltung',
    'button_download_new': '📥 Neuer Download',
    'button_broadcast_menu': '📢 Broadcast-Menü',
    'button_system_settings': '⚙️ Systemeinstellungen',
    'button_system_logs': '📋 Systemprotokolle',
    'button_create_backup': '💾 Backup erstellen',
    'button_restart_bot': '🔄 Bot neu starten',
    'button_maintenance_mode': '🛠️ Wartungsmodus',
    'button_performance_monitor': '📈 Leistungsüberwachung',
    'button_security_panel': '🛡️ Sicherheitsbereich',
    # Fehler
    'error_unknown_command': '❌ Unbekannter Befehl. Verwenden Sie /help für Hilfe.',
    'error_access_denied': '❌ Sie sind nicht berechtigt, auf diese Funktion zuzugreifen.',
    'error_critical': '🚨 Kritischer Bot-Fehler: {error}',
    'error_try_again': '❌ Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.',
    'msg_download_failed': '❌ Datei konnte nicht heruntergeladen werden. Bitte versuchen Sie es erneut oder überprüfen Sie den Link.',
    'msg_download_complete': '✅ Datei erfolgreich heruntergeladen!',
    'msg_user_info': 'Benutzerinfo:',
    'msg_badges': 'Abzeichen:',
    'msg_active_user_badge': 'Aktiver Benutzer',
    'button_user_analytics': 'Nutzeranalysen',
    'button_user_downloads': 'Meine Downloads',
    'button_privacy_settings': 'Datenschutzeinstellungen',
    'button_full_commands': 'Alle Befehle',
    'button_faq': 'FAQ',
    'button_support': 'Support',
    'button_terms': 'Nutzungsbedingungen',
    'msg_language_settings': 'Wählen Sie Ihre bevorzugte Sprache:',
    'button_language_fr': '🇫🇷 Französisch',
    'button_language_es': '🇪🇸 Spanisch',
    'button_language_de': '🇩🇪 Deutsch',
    'button_language_ru': '🇷🇺 Russisch',
    'msg_change_timezone': 'Zeitzone ändern',
    'msg_choose_timezone': 'Wählen Sie Ihre Zeitzone:',
    'button_timezone_baghdad': 'Bagdad',
    'button_timezone_new_york': 'New York',
    'button_timezone_moscow': 'Moskau',
    'button_timezone_beijing': 'Peking',
    'button_back_to_settings': 'Zurück zu den Einstellungen',
    'msg_manage_notifications': 'Benachrichtigungen verwalten',
    'msg_current_settings': 'Aktuelle Einstellungen:',
    'msg_download_notifications': 'Download-Benachrichtigungen',
    'msg_download_start': 'Download gestartet',
    'msg_download_complete': 'Download abgeschlossen',
    'msg_download_failed': 'Download fehlgeschlagen',
    'msg_system_notifications': 'Systembenachrichtigungen',
    'msg_bot_updates': 'Bot-Updates',
    'msg_admin_messages': 'Admin-Nachrichten',
    'msg_security_alerts': 'Sicherheitswarnungen',
    'msg_notification_timing': 'Benachrichtigungszeit',
    'msg_night_notifications': 'Nachtbenachrichtigungen',
    'msg_quiet_hours': 'Ruhezeiten',
    'msg_notification_type': 'Benachrichtigungstyp',
    'msg_sound_notifications': 'Tonbenachrichtigungen',
    'msg_vibration_notifications': 'Vibrationsbenachrichtigungen',
    'button_download_notifications': 'Download-Benachrichtigungen',
    'button_system_notifications': 'Systembenachrichtigungen',
    'button_notification_timing': 'Benachrichtigungszeit',
    'button_notification_type': 'Benachrichtigungstyp',
    'button_disable_all_notifications': 'Alle Benachrichtigungen deaktivieren',
    'button_enable_all_notifications': 'Alle Benachrichtigungen aktivieren',
    'msg_admin_menu': 'Admin-Menü',
    'button_admin_stats': 'Admin-Statistiken',
    'button_admin_users': 'Admin-Benutzer',
    'button_admin_broadcast': 'Broadcast',
    'button_admin_settings': 'Admin-Einstellungen',
    'button_admin_logs': 'Admin-Protokolle',
    'button_admin_backup': 'Backup',
    'button_confirm_broadcast': 'Broadcast bestätigen',
    'button_cancel_broadcast': 'Broadcast abbrechen',
    'button_broadcast_text': 'Text',
    'button_broadcast_photo': 'Foto',
    'button_broadcast_link': 'Link',
    'button_broadcast_poll': 'Umfrage',
    'button_broadcast_active': 'Nur aktive',
    'button_broadcast_premium': 'Nur Premium',
    'button_main_panel': 'Zurück zum Hauptmenü',
    'msg_detailed_report': 'Detaillierter Bericht',
    'button_check_subscription': 'Abonnement prüfen',
    'button_back': 'Zurück',
    # ... أكمل بقية المفاتيح حسب الحاجة ...
}
