translations = {
    # General messages
    'msg_welcome': '🎉 Welcome to the Smart Download Center!\nYour all-in-one solution for downloading videos and audio from the most popular platforms – easily and quickly.\n\n🔹 Supported Platforms:\nInstagram | Facebook | TikTok | Pinterest | Snapchat\n✔️ Direct download of video or audio from any link\n\n🔹 YouTube – Advanced Level:\n✔️ Download video or audio\n✔️ Full playlist support\n✔️ Browse the playlist, select specific files or download all\n✔️ Choose format: video or audio as you wish\n\n💡 All you have to do: just send the link\nI’ll handle the rest — accurately and fast.\n\n🚀 Ready? Start by sending your first link now.',
    'msg_help': '📝 Use /help to see all available commands',
    'msg_settings': '⚙️ Settings',
    'msg_error_unknown': '❌ An unexpected error occurred. Please try again later.',
    'msg_subscription_required': '🔒 To access all bot features, you must subscribe to the following channels first:\n\n{channels}\n\n✅ After subscribing, click the "Check Subscription" button below.\n\nIf the channels do not appear, please try again later.',
    'msg_profile': '👤 Your profile',
    'msg_stats': '📊 Your personal statistics',
    'msg_admin_panel': '👑 Admin Panel',
    'msg_broadcast': '📢 Send broadcast message',
    'msg_download_menu': '📥 Download files',
    'msg_detailed_report': '📊 Detailed report',
    'msg_no_stats': '❌ No statistics available',
    'msg_user_banned': '🚫 You have been banned from using the bot.\nReason: {reason}\n\nFor inquiries, contact the admin.',
    'msg_user_already_banned': '⚠️ User is already banned.',
    'msg_user_not_found': '❌ User not found.',
    'msg_ban_success': '✅ User banned successfully.',
    'msg_unban_success': '✅ User unbanned successfully.',
    'msg_maintenance': '🔧 Maintenance Notice\n\nSystem maintenance will be performed:\n📅 Date: {maintenance_date}\n⏰ Time: {maintenance_time}\n⏱️ Expected duration: {duration}\n\nWe apologize for any inconvenience.',
    'msg_system_update': '🆕 System Update\n\nA new update has been released for the bot:\n📋 Version: {version}\n✨ New features:\n{features}\n\nThe update is now available!',
    'msg_admin_message': '📢 Message from admin\n\n{message_content}',
    'msg_achievement': 'Congratulations! You have earned a new achievement:\n\n{achievement_icon} {achievement_name}\n{achievement_description}\n\n🏆 Points earned: {points_earned}',
    'msg_security_alert': '🚨 Security Alert\n\nAlert type: {alert_type}\nDetails: {details}\n\nPlease take appropriate action immediately.',
    'msg_user_info': 'User Info:',
    'msg_badges': 'Badges:',
    'msg_active_user_badge': 'Active User',
    'msg_language_settings': 'Choose your preferred language:',
    # General buttons
    'button_settings': '⚙️ Settings',
    'button_back': '🔙 Back',
    'button_language_ar': '🇮🇶 Arabic',
    'button_language_en': '🌐 English',
    'button_timezone': '⏰ Timezone',
    'button_notifications': '🔔 Notifications',
    'button_check_subscription': '✅ Check Subscription',
    'button_main_menu': '🏠 Main menu',
    'button_download_menu': '📥 Download files',
    'button_user_stats': '📊 My stats',
    'button_admin_panel': '👑 Admin Panel',
    'button_admin_stats': '📊 Bot statistics',
    'button_admin_users': '👥 User management',
    'button_admin_broadcast': '📢 Broadcast message',
    'button_admin_settings': '🔧 System settings',
    'button_admin_logs': '📋 System logs',
    'button_admin_backup': '💾 Backup',
    'button_admin_restart': '🔄 Restart',
    'button_admin_maintenance': '🔧 Maintenance mode',
    'button_admin_performance': '📈 Performance monitor',
    'button_admin_security': '🛡️ Security',
    'button_admin_detailed_stats': '📊 Detailed stats',
    'button_admin_users_management': '👥 User management',
    'button_admin_broadcast_menu': '📢 Broadcast menu',
    'button_admin_system_settings': '🔧 System settings',
    'button_admin_system_logs': '📋 System logs',
    'button_admin_create_backup': '💾 Backup',
    'button_admin_restart_bot': '🔄 Restart',
    'button_admin_maintenance_mode': '🔧 Maintenance mode',
    'button_admin_performance_monitor': '📈 Performance monitor',
    'button_admin_security_panel': '🛡️ Security Panel',
    'button_admin_toggle_rate_limit': '⚡ Rate limit',
    'button_admin_toggle_backup': '💾 Backups',
    'button_admin_toggle_analytics': '📊 Analytics',
    'button_admin_reset_settings': '🔄 Reset settings',
    'button_admin_main_panel': '🔙 Back to admin panel',
    'button_admin_broadcast_text': '📝 Text message',
    'button_admin_broadcast_photo': '🖼️ Photo message',
    'button_admin_broadcast_link': '🔗 Link message',
    'button_admin_broadcast_poll': '📊 Poll',
    'button_admin_broadcast_active': '👥 Active users',
    'button_admin_broadcast_premium': '⭐ Premium users',
    'button_help': '🆘 Help',
    'button_detailed_stats': '📊 Detailed Stats',
    'button_download_history': '📥 Download History',
    'button_users_management': '👥 Users Management',
    'button_download_new': '📥 New Download',
    'button_system_settings': '⚙️ System Settings',
    'button_system_logs': '📋 System Logs',
    'button_create_backup': '💾 Create Backup',
    'button_restart_bot': '🔄 Restart Bot',
    'button_maintenance_mode': '🛠️ Maintenance Mode',
    'button_performance_monitor': '📈 Performance Monitor',
    'button_security_panel': '🛡️ Security Panel',
    'button_user_analytics': 'User Analytics',
    'button_user_downloads': 'My Downloads',
    'button_privacy_settings': 'Privacy Settings',
    'button_full_commands': 'All Commands',
    'button_faq': 'FAQ',
    'button_support': 'Support',
    'button_terms': 'Terms & Conditions',
    # User settings
    'button_user_set_language_ar': '🇮🇶 Arabic',
    'button_user_set_language_en': '🌐 English',
    'button_user_set_timezone_baghdad': 'Baghdad (UTC+3)',
    'button_user_set_timezone_newyork': 'New York (UTC-5)',
    'button_user_set_timezone_moscow': 'Moscow (UTC+3)',
    'button_user_set_timezone_beijing': 'Beijing (UTC+8)',
    'button_user_download_notifications': '📥 Download notifications',
    'button_user_system_notifications': '🔔 System notifications',
    'button_user_notification_timing': '⏰ Notification timing',
    'button_user_notification_type': '🔊 Notification type',
    'button_user_disable_all_notifications': '🚫 Disable all notifications',
    'button_user_enable_all_notifications': '🔔 Enable all notifications',
    'button_language_fr': '🇫🇷 French',
    'button_language_es': '🇪🇸 Spanish',
    'button_language_de': '🇩🇪 German',
    'button_language_ru': '🇷🇺 Russian',
    # Errors
    'error_unknown_command': '❌ Unknown command. Use /help for assistance.',
    'error_access_denied': '❌ You are not authorized to access this feature.',
    'error_critical': '🚨 Critical bot error: {error}',
    'error_try_again': '❌ An unexpected error occurred. Please try again later.',
    'error_no_stats': '❌ No statistics available',
    'error_no_permission': '❌ You do not have permission to perform this action.',
    'error_not_found': '❌ The requested item was not found.',
    'error_already_exists': '⚠️ Item already exists.',
    # Notifications
    'notif_download_start': 'Started downloading file: {filename}\nSize: {file_size_mb} MB',
    'notif_download_complete': '✅ File downloaded successfully!',
    'notif_download_failed': '❌ Failed to download the file. Please try again or check the link.',
    'notif_achievement': 'Congratulations! You have earned a new achievement:\n\n{achievement_icon} {achievement_name}\n{achievement_description}\n\n🏆 Points earned: {points_earned}',
    'notif_security_alert': '🚨 Security Alert\n\nAlert type: {alert_type}\nDetails: {details}\n\nPlease take appropriate action immediately.',
    'notif_maintenance': '🔧 Maintenance Notice\n\nSystem maintenance will be performed:\n📅 Date: {maintenance_date}\n⏰ Time: {maintenance_time}\n⏱️ Expected duration: {duration}\n\nWe apologize for any inconvenience.',
    'notif_system_update': '🆕 System Update\n\nA new update has been released for the bot:\n📋 Version: {version}\n✨ New features:\n{features}\n\nThe update is now available!',
    'notif_admin_message': '📢 Message from admin\n\n{message_content}',
    'msg_change_timezone': 'Change Timezone',
    'msg_choose_timezone': 'Choose your timezone:',
    'button_timezone_riyadh': 'Riyadh',
    'button_timezone_baghdad': 'Baghdad',
    'button_timezone_dubai': 'Dubai',
    'button_timezone_kuwait': 'Kuwait',
    'button_timezone_bahrain': 'Bahrain',
    'button_timezone_muscat': 'Muscat',
    'button_timezone_qatar': 'Qatar',
    'button_timezone_newyork': 'New York',
    'button_timezone_moscow': 'Moscow',
    'button_timezone_beijing': 'Beijing',
    'button_back_to_settings': 'Back to Settings',
    'msg_manage_notifications': 'Manage Notifications',
    'msg_current_settings': 'Current Settings:',
    'msg_download_notifications': 'Download Notifications',
    'msg_download_start': 'Download Started',
    'msg_download_complete': 'Download Complete',
    'msg_download_failed': 'Download Failed',
    'msg_system_notifications': 'System Notifications',
    'msg_bot_updates': 'Bot Updates',
    'msg_admin_messages': 'Admin Messages',
    'msg_security_alerts': 'Security Alerts',
    'msg_notification_timing': 'Notification Timing',
    'msg_night_notifications': 'Night Notifications',
    'msg_quiet_hours': 'Quiet Hours',
    'msg_notification_type': 'Notification Type',
    'msg_sound_notifications': 'Sound Notifications',
    'msg_vibration_notifications': 'Vibration Notifications',
    'button_download_notifications': 'Download Notifications',
    'button_system_notifications': 'System Notifications',
    'button_notification_timing': 'Notification Timing',
    'button_notification_type': 'Notification Type',
    'button_disable_all_notifications': 'Disable All Notifications',
    'button_enable_all_notifications': 'Enable All Notifications',
    'msg_admin_menu': 'Admin Menu',
    'button_admin_stats': 'Admin Stats',
    'button_admin_users': 'Admin Users',
    'button_admin_broadcast': 'Broadcast',
    'button_admin_settings': 'Admin Settings',
    'button_admin_logs': 'Admin Logs',
    'button_admin_backup': 'Backup',
    'button_confirm_broadcast': 'Confirm Broadcast',
    'button_cancel_broadcast': 'Cancel Broadcast',
    'button_broadcast_text': 'Text',
    'button_broadcast_photo': 'Photo',
    'button_broadcast_link': 'Link',
    'button_broadcast_poll': 'Poll',
    'button_broadcast_active': 'Active Only',
    'button_broadcast_premium': 'Premium Only',
    'button_main_panel': 'Back to Main Panel',
}
