translations = {
    # Mensajes generales
    'msg_welcome': '🎉 ¡Bienvenido al Centro de Descargas Inteligente!\nTu solución integral para descargar videos y audios de las plataformas más populares – fácil y rápido.\n\n🔹 Plataformas compatibles:\nInstagram | Facebook | TikTok | Pinterest | Snapchat\n✔️ Descarga directa de video o audio desde cualquier enlace\n\n🔹 YouTube – Nivel avanzado:\n✔️ Descarga de video o audio\n✔️ Soporte completo para listas de reproducción\n✔️ Navega por la lista, selecciona archivos específicos o descarga todo\n✔️ Elige el formato: video o audio como prefieras\n\n💡 Solo tienes que enviar el enlace\nYo me encargo del resto — con precisión y rapidez.\n\n🚀 ¿Listo? Comienza enviando tu primer enlace ahora.',
    'msg_help': '📝 Usa /help para ver todos los comandos disponibles',
    'msg_settings': '⚙️ Configuración',
    'msg_error_unknown': '❌ Ocurrió un error inesperado. Por favor, inténtalo de nuevo más tarde.',
    'msg_subscription_required': '🔒 Para acceder a todas las funciones del bot, primero debes suscribirte a los siguientes canales:\n\n{channels}\n\n✅ Después de suscribirte, haz clic en el botón "Verificar suscripción" abajo.\n\nSi los canales no aparecen, inténtalo de nuevo más tarde.',
    'msg_profile': '👤 Tu perfil',
    'msg_stats': '📊 Tus estadísticas personales',
    'msg_admin_panel': '👑 Panel de administración',
    'msg_broadcast': '📢 Enviar mensaje de difusión',
    'msg_download_menu': '📥 Descargar archivos',
    'msg_detailed_report': '📊 Informe detallado',
    'msg_no_stats': '❌ No hay estadísticas disponibles',
    'msg_user_banned': '🚫 Has sido baneado del bot.\nRazón: {reason}\n\nPara consultas, contacta al administrador.',
    'msg_user_already_banned': '⚠️ El usuario ya está baneado.',
    'msg_user_not_found': '❌ Usuario no encontrado.',
    'msg_ban_success': '✅ Usuario baneado con éxito.',
    'msg_unban_success': '✅ Usuario desbaneado con éxito.',
    'msg_maintenance': '🔧 Aviso de mantenimiento\n\nSe realizará un mantenimiento del sistema:\n📅 Fecha: {maintenance_date}\n⏰ Hora: {maintenance_time}\n⏱️ Duración esperada: {duration}\n\nDisculpa las molestias.',
    'msg_system_update': '🆕 Actualización del sistema\n\nSe ha lanzado una nueva actualización del bot:\n📋 Versión: {version}\n✨ Nuevas funciones:\n{features}\n\n¡La actualización ya está disponible!',
    'msg_admin_message': '📢 Mensaje del administrador\n\n{message_content}',
    'msg_achievement': '¡Felicidades! Has conseguido un nuevo logro:\n\n{achievement_icon} {achievement_name}\n{achievement_description}\n\n🏆 Puntos obtenidos: {points_earned}',
    'msg_security_alert': '🚨 Alerta de seguridad\n\nTipo de alerta: {alert_type}\nDetalles: {details}\n\nPor favor, toma las medidas adecuadas de inmediato.',
    # Botones generales
    'button_settings': '⚙️ Configuración',
    'button_back': '🔙 Atrás',
    'button_language_ar': '🇮🇶 Árabe',
    'button_language_en': '🌐 Inglés',
    'button_timezone': '⏰ Zona horaria',
    'button_notifications': '🔔 Notificaciones',
    'button_check_subscription': '✅ Verificar suscripción',
    'button_main_menu': '🏠 Menú principal',
    'button_download_menu': '📥 Descargar archivos',
    'button_user_stats': '📊 Mis estadísticas',
    'button_admin_panel': '👑 Panel de administración',
    'button_admin_stats': '📊 Estadísticas del bot',
    'button_admin_users': '👥 Gestión de usuarios',
    'button_admin_broadcast': '📢 Mensaje de difusión',
    'button_admin_settings': '🔧 Configuración del sistema',
    'button_admin_logs': '📋 Registros del sistema',
    'button_admin_backup': '💾 Copia de seguridad',
    'button_admin_restart': '🔄 Reiniciar',
    'button_admin_maintenance': '🔧 Modo de mantenimiento',
    'button_admin_performance': '📈 Monitor de rendimiento',
    'button_admin_security': '🛡️ Seguridad',
    'button_admin_detailed_stats': '📊 Estadísticas detalladas',
    'button_admin_users_management': '👥 Gestión de usuarios',
    'button_admin_broadcast_menu': '📢 Menú de difusión',
    'button_admin_system_settings': '🔧 Configuración del sistema',
    'button_admin_system_logs': '📋 Registros del sistema',
    'button_admin_create_backup': '💾 Copia de seguridad',
    'button_admin_restart_bot': '🔄 Reiniciar',
    'button_admin_maintenance_mode': '🔧 Modo de mantenimiento',
    'button_admin_performance_monitor': '📈 Monitor de rendimiento',
    'button_admin_security_panel': '🛡️ Panel de seguridad',
    'button_admin_toggle_rate_limit': '⚡ Límite de velocidad',
    'button_admin_toggle_backup': '💾 Copias de seguridad',
    'button_admin_toggle_analytics': '📊 Analíticas',
    'button_admin_reset_settings': '🔄 Restablecer configuración',
    'button_admin_main_panel': '🔙 Volver al panel de administración',
    'button_admin_broadcast_text': '📝 Mensaje de texto',
    'button_admin_broadcast_photo': '🖼️ Mensaje con foto',
    'button_admin_broadcast_link': '🔗 Mensaje con enlace',
    'button_admin_broadcast_poll': '📊 Encuesta',
    'button_admin_broadcast_active': '👥 Usuarios activos',
    'button_admin_broadcast_premium': '⭐ Usuarios premium',
    'button_help': '🆘 Ayuda',
    'button_detailed_stats': '📊 Estadísticas detalladas',
    'button_download_history': '📥 Historial de descargas',
    'button_users_management': '👥 Gestión de usuarios',
    'button_download_new': '📥 Nueva descarga',
    'button_restart_bot': '🔄 Reiniciar bot',
    'button_maintenance_mode': '🛠️ Modo mantenimiento',
    # Configuración de usuario
    'button_user_set_language_ar': '🇮🇶 Árabe',
    'button_user_set_language_en': '🌐 Inglés',
    'button_user_set_timezone_baghdad': 'Bagdad (UTC+3)',
    'button_user_set_timezone_newyork': 'Nueva York (UTC-5)',
    'button_user_set_timezone_moscow': 'Moscú (UTC+3)',
    'button_user_set_timezone_beijing': 'Pekín (UTC+8)',
    'button_user_download_notifications': '📥 Notificaciones de descarga',
    'button_user_system_notifications': '🔔 Notificaciones del sistema',
    'button_user_notification_timing': '⏰ Horario de notificaciones',
    'button_user_notification_type': '🔊 Tipo de notificación',
    'button_user_disable_all_notifications': '🚫 Desactivar todas las notificaciones',
    'button_user_enable_all_notifications': '🔔 Activar todas las notificaciones',
    # Errores
    'error_unknown_command': '❌ Comando desconocido. Usa /help para obtener ayuda.',
    'error_access_denied': '❌ No tienes autorización para acceder a esta función.',
    'error_critical': '🚨 Error crítico del bot: {error}',
    'error_try_again': '❌ Ocurrió un error inesperado. Por favor, inténtalo de nuevo más tarde.',
    'error_no_stats': '❌ No hay estadísticas disponibles',
    'error_no_permission': '❌ No tienes permiso para realizar esta acción.',
    'error_not_found': '❌ No se encontró el elemento solicitado.',
    'error_already_exists': '⚠️ El elemento ya existe.',
    # Notificaciones
    'notif_download_start': 'Comenzó la descarga del archivo: {filename}\nTamaño: {file_size_mb} MB',
    'notif_download_complete': '✅ ¡Archivo descargado con éxito!',
    'notif_download_failed': 'Error al descargar el archivo: {filename}\nRazón: {error_message}',
    'notif_achievement': '¡Felicidades! Has conseguido un nuevo logro:\n\n{achievement_icon} {achievement_name}\n{achievement_description}\n\n🏆 Puntos obtenidos: {points_earned}',
    'notif_security_alert': '🚨 Alerta de seguridad\n\nTipo de alerta: {alert_type}\nDetalles: {details}\n\nPor favor, toma las medidas adecuadas de inmediato.',
    'notif_maintenance': '🔧 Aviso de mantenimiento\n\nSe realizará un mantenimiento del sistema:\n📅 Fecha: {maintenance_date}\n⏰ Hora: {maintenance_time}\n⏱️ Duración esperada: {duration}\n\nDisculpa las molestias.',
    'notif_system_update': '🆕 Actualización del sistema\n\nSe ha lanzado una nueva actualización del bot:\n📋 Versión: {version}\n✨ Nuevas funciones:\n{features}\n\n¡La actualización ya está disponible!',
    'notif_admin_message': '📢 Mensaje del administrador\n\n{message_content}',
    'msg_download_failed': '❌ Error al descargar el archivo. Por favor, inténtalo de nuevo o verifica el enlace.',
    'button_create_backup': '💾 Crear copia de seguridad',
    'button_performance_monitor': '📈 Monitor de rendimiento',
    'msg_user_info': 'Información del usuario:',
    'msg_badges': 'Insignias:',
    'msg_active_user_badge': 'Usuario activo',
    'button_user_analytics': 'Analítica de usuario',
    'button_user_downloads': 'Mis descargas',
    'button_privacy_settings': 'Configuración de privacidad',
    'button_full_commands': 'Todos los comandos',
    'button_faq': 'Preguntas frecuentes',
    'button_support': 'Soporte',
    'button_terms': 'Términos y condiciones',
    'msg_language_settings': 'Elige tu idioma preferido:',
    'button_language_fr': '🇫🇷 Francés',
    'button_language_es': '🇪🇸 Español',
    'button_language_de': '🇩🇪 Alemán',
    'button_language_ru': '🇷🇺 Ruso',
    'msg_change_timezone': 'Cambiar zona horaria',
    'msg_choose_timezone': 'Elige tu zona horaria:',
    'button_timezone_baghdad': 'Bagdad',
    'button_timezone_new_york': 'Nueva York',
    'button_timezone_moscow': 'Moscú',
    'button_timezone_beijing': 'Pekín',
    'button_back_to_settings': 'Volver a configuración',
    'msg_manage_notifications': 'Gestionar notificaciones',
    'msg_current_settings': 'Configuración actual:',
    'msg_download_notifications': 'Notificaciones de descarga',
    'msg_download_start': 'Descarga iniciada',
    'msg_download_complete': 'Descarga completada',
    'msg_download_failed': 'Descarga fallida',
    'msg_system_notifications': 'Notificaciones del sistema',
    'msg_bot_updates': 'Actualizaciones del bot',
    'msg_admin_messages': 'Mensajes de admin',
    'msg_security_alerts': 'Alertas de seguridad',
    'msg_notification_timing': 'Horario de notificaciones',
    'msg_night_notifications': 'Notificaciones nocturnas',
    'msg_quiet_hours': 'Horas de silencio',
    'msg_notification_type': 'Tipo de notificación',
    'msg_sound_notifications': 'Notificaciones de sonido',
    'msg_vibration_notifications': 'Notificaciones de vibración',
    'button_download_notifications': 'Notificaciones de descarga',
    'button_system_notifications': 'Notificaciones del sistema',
    'button_notification_timing': 'Horario de notificaciones',
    'button_notification_type': 'Tipo de notificación',
    'button_disable_all_notifications': 'Desactivar todas las notificaciones',
    'button_enable_all_notifications': 'Activar todas las notificaciones',
    'msg_admin_menu': 'Menú de administración',
    'button_admin_stats': 'Estadísticas admin',
    'button_admin_users': 'Usuarios admin',
    'button_admin_broadcast': 'Difusión',
    'button_admin_settings': 'Configuración admin',
    'button_admin_logs': 'Registros admin',
    'button_admin_backup': 'Copia de seguridad',
    'button_confirm_broadcast': 'Confirmar difusión',
    'button_cancel_broadcast': 'Cancelar difusión',
    'button_broadcast_text': 'Texto',
    'button_broadcast_photo': 'Foto',
    'button_broadcast_link': 'Enlace',
    'button_broadcast_poll': 'Encuesta',
    'button_broadcast_active': 'Solo activos',
    'button_broadcast_premium': 'Solo premium',
    'button_main_panel': 'Volver al panel principal',
}
