translations = {
    # Messages généraux
    'msg_welcome': '🎉 Bienvenue au Centre de Téléchargement Intelligent !\nVotre solution tout-en-un pour télécharger des vidéos et de l’audio depuis les plateformes les plus populaires – facilement et rapidement.\n\n🔹 Plateformes prises en charge :\nInstagram | Facebook | TikTok | Pinterest | Snapchat\n✔️ Téléchargement direct de vidéos ou d’audio à partir de n’importe quel lien\n\n🔹 YouTube – Niveau avancé :\n✔️ Téléchargement de vidéos ou d’audio\n✔️ Prise en charge complète des playlists\n✔️ Parcourez la playlist, sélectionnez des fichiers spécifiques ou téléchargez tout\n✔️ Choisissez le format : vidéo ou audio selon votre choix\n\n💡 Il vous suffit d’envoyer le lien\nJe m’occupe du reste — avec précision et rapidité.\n\n🚀 Prêt ? Commencez par envoyer votre premier lien maintenant.',
    'msg_help': '📝 Utilisez /help pour voir toutes les commandes disponibles',
    'msg_settings': '⚙️ Paramètres',
    'msg_error_unknown': '❌ Une erreur inattendue s\'est produite. Veuillez réessayer plus tard.',
    'msg_subscription_required': '🔒 Pour accéder à toutes les fonctionnalités du bot, vous devez d’abord vous abonner aux chaînes suivantes :\n\n{channels}\n\n✅ Après l’abonnement, cliquez sur le bouton "Vérifier l’abonnement" ci-dessous.\n\nSi les chaînes n’apparaissent pas, réessayez plus tard.',
    'msg_profile': '👤 Votre profil',
    'msg_stats': '📊 Vos statistiques personnelles',
    'msg_admin_panel': '👑 Panneau d\'administration',
    'msg_broadcast': '📢 Envoyer un message de diffusion',
    'msg_download_menu': '📥 Télécharger des fichiers',
    'msg_detailed_report': '📊 Rapport détaillé',
    'msg_no_stats': '❌ Aucune statistique disponible',
    'msg_user_banned': '🚫 Vous avez été banni du bot.\nRaison : {reason}\n\nPour toute question, contactez l\'administrateur.',
    'msg_user_already_banned': '⚠️ L\'utilisateur est déjà banni.',
    'msg_user_not_found': '❌ Utilisateur non trouvé.',
    'msg_ban_success': '✅ Utilisateur banni avec succès.',
    'msg_unban_success': '✅ Bannissement levé avec succès.',
    'msg_maintenance': '🔧 Avis de maintenance\n\nUne maintenance du système sera effectuée :\n📅 Date : {maintenance_date}\n⏰ Heure : {maintenance_time}\n⏱️ Durée prévue : {duration}\n\nNous nous excusons pour la gêne occasionnée.',
    'msg_system_update': '🆕 Mise à jour du système\n\nUne nouvelle mise à jour a été publiée :\n📋 Version : {version}\n✨ Nouvelles fonctionnalités :\n{features}\n\nLa mise à jour est maintenant disponible !',
    'msg_admin_message': '📢 Message de l\'administrateur\n\n{message_content}',
    'msg_achievement': 'Félicitations ! Vous avez obtenu un nouveau succès :\n\n{achievement_icon} {achievement_name}\n{achievement_description}\n\n🏆 Points gagnés : {points_earned}',
    'msg_security_alert': '🚨 Alerte de sécurité\n\nType d\'alerte : {alert_type}\nDétails : {details}\n\nVeuillez agir immédiatement.',
    # Boutons généraux
    'button_settings': '⚙️ Paramètres',
    'button_back': '🔙 Retour',
    'button_language_ar': '🇮🇶 Arabe',
    'button_language_en': '🌐 Anglais',
    'button_timezone': '⏰ Fuseau horaire',
    'button_notifications': '🔔 Notifications',
    'button_check_subscription': '✅ Vérifier l’abonnement',
    'button_main_menu': '🏠 Menu principal',
    'button_download_menu': '📥 Télécharger des fichiers',
    'button_user_stats': '📊 Mes statistiques',
    'button_admin_panel': '👑 Panneau d\'administration',
    'button_admin_stats': '📊 Statistiques du bot',
    'button_admin_users': '👥 Gestion des utilisateurs',
    'button_admin_broadcast': '📢 Message de diffusion',
    'button_admin_settings': '🔧 Paramètres du système',
    'button_admin_logs': '📋 Journaux du système',
    'button_admin_backup': '💾 Sauvegarde',
    'button_admin_restart': '🔄 Redémarrer',
    'button_admin_maintenance': '🔧 Mode maintenance',
    'button_admin_performance': '📈 Surveillance des performances',
    'button_admin_security': '🛡️ Sécurité',
    'button_admin_detailed_stats': '📊 Statistiques détaillées',
    'button_admin_users_management': '👥 Gestion des utilisateurs',
    'button_admin_broadcast_menu': '📢 Menu de diffusion',
    'button_admin_system_settings': '🔧 Paramètres du système',
    'button_admin_system_logs': '📋 Journaux du système',
    'button_admin_create_backup': '💾 Sauvegarde',
    'button_admin_restart_bot': '🔄 Redémarrer',
    'button_admin_maintenance_mode': '🔧 Mode maintenance',
    'button_admin_performance_monitor': '📈 Surveillance des performances',
    'button_admin_security_panel': '🛡️ Panneau de sécurité',
    'button_admin_toggle_rate_limit': '⚡ Limite de débit',
    'button_admin_toggle_backup': '💾 Sauvegardes',
    'button_admin_toggle_analytics': '📊 Analyses',
    'button_admin_reset_settings': '🔄 Réinitialiser les paramètres',
    'button_admin_main_panel': '🔙 Retour au panneau admin',
    'button_admin_broadcast_text': '📝 Message texte',
    'button_admin_broadcast_photo': '🖼️ Message photo',
    'button_admin_broadcast_link': '🔗 Message lien',
    'button_admin_broadcast_poll': '📊 Sondage',
    'button_admin_broadcast_active': '👥 Utilisateurs actifs',
    'button_admin_broadcast_premium': '⭐ Utilisateurs premium',
    'button_help': '🆘 Aide',
    'button_detailed_stats': '📊 Statistiques détaillées',
    'button_download_history': '📥 Historique des téléchargements',
    'button_users_management': '👥 Gestion des utilisateurs',
    'button_download_new': '📥 Nouveau téléchargement',
    'button_system_logs': '📋 Journaux du système',
    'button_create_backup': '💾 Créer une sauvegarde',
    'button_restart_bot': '🔄 Redémarrer le bot',
    'button_maintenance_mode': '🛠️ Mode maintenance',
    'button_performance_monitor': '📈 Surveillance des performances',
    'msg_download_complete': '✅ Fichier téléchargé avec succès !',
    # Paramètres utilisateur
    'button_user_set_language_ar': '🇮🇶 Arabe',
    'button_user_set_language_en': '🌐 Anglais',
    'button_user_set_timezone_baghdad': 'Bagdad (UTC+3)',
    'button_user_set_timezone_newyork': 'New York (UTC-5)',
    'button_user_set_timezone_moscow': 'Moscou (UTC+3)',
    'button_user_set_timezone_beijing': 'Pékin (UTC+8)',
    'button_user_download_notifications': '📥 Notifications de téléchargement',
    'button_user_system_notifications': '🔔 Notifications système',
    'button_user_notification_timing': '⏰ Heure des notifications',
    'button_user_notification_type': '🔊 Type de notification',
    'button_user_disable_all_notifications': '🚫 Désactiver toutes les notifications',
    'button_user_enable_all_notifications': '🔔 Activer toutes les notifications',
    # Erreurs
    'error_unknown_command': '❌ Commande inconnue. Utilisez /help pour obtenir de l\'aide.',
    'error_access_denied': '❌ Vous n\'êtes pas autorisé à accéder à cette fonctionnalité.',
    'error_critical': '🚨 Erreur critique du bot : {error}',
    'error_try_again': '❌ Une erreur inattendue s\'est produite. Veuillez réessayer plus tard.',
    'error_no_stats': '❌ Aucune statistique disponible',
    'error_no_permission': '❌ Vous n\'avez pas la permission d\'effectuer cette action.',
    'error_not_found': '❌ Élément demandé introuvable.',
    'error_already_exists': '⚠️ Élément déjà existant.',
    # Notifications
    'notif_download_start': 'Début du téléchargement du fichier : {filename}\nTaille : {file_size_mb} MB',
    'notif_download_complete': '✅ Fichier téléchargé avec succès !',
    'notif_download_failed': '❌ Échec du téléchargement du fichier. Veuillez réessayer ou vérifier le lien.',
    'notif_achievement': 'Félicitations ! Vous avez obtenu un nouveau succès :\n\n{achievement_icon} {achievement_name}\n{achievement_description}\n\n🏆 Points gagnés : {points_earned}',
    'notif_security_alert': '🚨 Alerte de sécurité\n\nType d\'alerte : {alert_type}\nDétails : {details}\n\nVeuillez agir immédiatement.',
    'notif_maintenance': '🔧 Avis de maintenance\n\nUne maintenance du système sera effectuée :\n📅 Date : {maintenance_date}\n⏰ Heure : {maintenance_time}\n⏱️ Durée prévue : {duration}\n\nNous nous excusons pour la gêne occasionnée.',
    'notif_system_update': '🆕 Mise à jour du système\n\nUne nouvelle mise à jour a été publiée :\n📋 Version : {version}\n✨ Nouvelles fonctionnalités :\n{features}\n\nLa mise à jour est maintenant disponible !',
    'notif_admin_message': '📢 Message de l\'administrateur\n\n{message_content}',
    'msg_user_info': 'Infos utilisateur :',
    'msg_badges': 'Badges :',
    'msg_active_user_badge': 'Utilisateur actif',
    'button_user_analytics': 'Analyses utilisateur',
    'button_user_downloads': 'Mes téléchargements',
    'button_privacy_settings': 'Paramètres de confidentialité',
    'button_full_commands': 'Toutes les commandes',
    'button_faq': 'FAQ',
    'button_support': 'Support',
    'button_terms': 'Conditions générales',
    'msg_language_settings': 'Choisissez votre langue préférée :',
    'button_language_fr': '🇫🇷 Français',
    'button_language_es': '🇪🇸 Espagnol',
    'button_language_de': '🇩🇪 Allemand',
    'button_language_ru': '🇷🇺 Russe',
    'msg_change_timezone': 'Changer de fuseau horaire',
    'msg_choose_timezone': 'Choisissez votre fuseau horaire :',
    'button_timezone_baghdad': 'Bagdad',
    'button_timezone_new_york': 'New York',
    'button_timezone_moscow': 'Moscou',
    'button_timezone_beijing': 'Pékin',
    'button_back_to_settings': 'Retour aux paramètres',
    'msg_manage_notifications': 'Gérer les notifications',
    'msg_current_settings': 'Paramètres actuels :',
    'msg_download_notifications': 'Notifications de téléchargement',
    'msg_download_start': 'Début du téléchargement',
    'msg_download_complete': 'Téléchargement terminé',
    'msg_download_failed': 'Échec du téléchargement',
    'msg_system_notifications': 'Notifications système',
    'msg_bot_updates': 'Mises à jour du bot',
    'msg_admin_messages': 'Messages administrateur',
    'msg_security_alerts': 'Alertes de sécurité',
    'msg_notification_timing': 'Heure des notifications',
    'msg_night_notifications': 'Notifications nocturnes',
    'msg_quiet_hours': 'Heures calmes',
    'msg_notification_type': 'Type de notification',
    'msg_sound_notifications': 'Notifications sonores',
    'msg_vibration_notifications': 'Notifications par vibration',
    'button_download_notifications': 'Notifications de téléchargement',
    'button_system_notifications': 'Notifications système',
    'button_notification_timing': 'Heure des notifications',
    'button_notification_type': 'Type de notification',
    'button_disable_all_notifications': 'Désactiver toutes les notifications',
    'button_enable_all_notifications': 'Activer toutes les notifications',
    'msg_admin_menu': 'Menu administrateur',
    'button_admin_stats': 'Statistiques admin',
    'button_admin_users': 'Utilisateurs admin',
    'button_admin_broadcast': 'Diffusion',
    'button_admin_settings': 'Paramètres admin',
    'button_admin_logs': 'Journaux admin',
    'button_admin_backup': 'Sauvegarde',
    'button_confirm_broadcast': 'Confirmer la diffusion',
    'button_cancel_broadcast': 'Annuler la diffusion',
    'button_broadcast_text': 'Texte',
    'button_broadcast_photo': 'Photo',
    'button_broadcast_link': 'Lien',
    'button_broadcast_poll': 'Sondage',
    'button_broadcast_active': 'Actifs uniquement',
    'button_broadcast_premium': 'Premium uniquement',
    'button_main_panel': 'Retour au panneau principal',
}
